### PR TITLE
Fixes for encryption 

### PR DESCRIPTION
**Pull request by willwade**

### CODE REVIEW

**Comment by willwade** [comment]
I think we are missing configure_enc_utils in GUI dir as its referencing that  - and he config.enc in that dir, But somethings not right with that either as if I copy them bot into the widget dir i get

  Traceback (most recent call last):
    File "C:\GitHub\TranslateAndTTS\GUI_TranslateAndTTS\widget.py", line 1751, in <module>
      ms_token = config.get("azureTTS")["key"]
                 ^^^^^^^^^^
  AttributeError: 'NoneType' object has no attribute 'get'

NB: - Make sure we reference config.enc to the same dir as settings.cfg - i say we just embed the key methods in widget.py

**Comment by acerjay** [comment]
> I think we are missing configure_enc_utils in GUI dir as its referencing that - and he config.enc in that dir, But somethings not right with that either as if I copy them both into the widget dir i get
> 
> Traceback (most recent call last): File "C:\GitHub\TranslateAndTTS\GUI_TranslateAndTTS\widget.py", line 1751, in ms_token = config.get("azureTTS")["key"] ^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'get'
> 
> NB: - Make sure we reference config.enc to the same dir as settings.cfg - i say we just embed the key methods in widget.py
load config added more lines of repeated code. i'm hoping this hack will save the day :D 
image
Moreover, both of the GUI and Client is in the same folder so i think it is safe.
Re: on Azure error, maybe setting.cfg is not included during your copy? I hope my added code fix the issue.

**Comment by willwade** [comment]
I have a feeling it will always fail that workflow as the env cant be applied to PR.. 

Running locally it makes it fine - but when I run widget.py I see

Traceback (most recent call last):
  File "C:\GitHub\TranslateAndTTS\GUI_TranslateAndTTS\widget.py", line 1751, in <module>
    ms_token = config.get("azureTTS")["key"]
               ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

so config is being set to None. Interesting.

**Comment by willwade** [comment]
I think for me your sys.path append trick isnt working.. im going to merge and see what happens on GH and automated build.

**Pull request merged**
